execution_engine: asyncio
logger:
  transports: [console, file]
  level: debug
  progress_display: true
  path_settings:
    path_pattern: "logs/mcp-agent-{unique_id}.jsonl"
    unique_id: "timestamp"
    timestamp_format: "%Y-%m-%dT%H:%M:%S"

mcp:
  servers:
  
    scholar:
      command: "/home/rathindra/julia_python_project/pyjulia_env/bin/python"
      args: ["/home/rathindra/julia_python_project/mcp/langchainmcp/tool.py"]

    arxiv-mcp-server:  
      command: uv  
      args:  
        - --directory  
        - /home/rathindra/julia_python_project/mcp/arxiv-mcp-server
        - run  
        - arxiv-mcp-server  
        - --storage-path  
        - /home/rathindra/julia_python_project/mcp/arxiv-mcp-server/papers




openai:
  base_url: https://openrouter.ai/api/v1
  default_model: openai/gpt-4.1-mini
  api_key: #api_key


